# Плагин raiSnowMan v1.0 написан Exosmium (vk.com/lovelygalaxy)

name: raiSnowMan
version: '${project.version}'
main: lv.exosmium.raisnowman.Main
authors: [ Exosmium ]
commands:
  snowman:
    description: Призовите снеговика!
    usage: /snowman